name: Node.js Workflow

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: Abschlussprojekt  # Zielverzeichnis für das Repository

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
        working-directory: Abschlussprojekt  # Arbeitsverzeichnis für den Schritt festlegen

      - name: Run Tests
        run: npm test
        working-directory: Abschlussprojekt  # Arbeitsverzeichnis für den Schritt festlegen
     
